version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run: apk update
      - run: apk add python2
      - run: echo ${TAG}; if [ -z ${TAG+x} ]; then TAG=$CIRCLE_BRANCH; fi; if [ $TAG=="master" ]; then TAG="latest"; fi; echo export TAG=\"$TAG\" >> $BASH_ENV; source $BASH_ENV; echo $BASH_ENV
      - run: python process_build.py $TAG
      - run: source $BASH_ENV; docker build -t tylerthepug/crypt-server-saml:$TAG .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: source $BASH_ENV; docker push tylerthepug/crypt-server-saml:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
